# general
gpu_id: 0
use_gpu: True
seed: 2020
reproducibility: True
state: INFO
data_path: 'dataset/'
checkpoint_dir: 'saved'
show_progress: True
density: [ 0.05, 0.1, 0.15, 0.2 ]
dataset_type: [ 'rt', 'tp' ]

# training settings
epochs: 200
train_batch_size: 128
learner: adam
learning_rate: 0.001
weight_decay: 0.0
eval_step: 10
stopping_step: ~
loss_decimal_place: 4

# evaluation settings
metrics: [ 'MAE', 'RMSE' ]
eval_batch_size: 128
metric_decimal_place: 4
